#!/usr/bin/env bash

# Resolve absolute paths.
CURRENT_DIR=$(cd $(dirname "$0"); pwd)
SOURCE_DIR=$(cd "$CURRENT_DIR/.."; pwd)

mkdir -p "$SOURCE_DIR/ios/gen"

INPUT_FILES=(
    "promise-polyfill.js"
    "typedarray.js"
    "error-polyfill.js"
    "jsbi.js"
)

OUTPUT_FILE="$SOURCE_DIR/ios/gen/polyfill.c"

cd "$SOURCE_DIR/ios/V82JSC/polyfill"
printf "/* Autogenerated.  Do not edit. */\n" > "$OUTPUT_FILE"
for INFILE in "${INPUT_FILES[@]}";
do
   xxd -i "$INFILE" >> "$OUTPUT_FILE"
   printf "\n/*-------*/\n" >> "$OUTPUT_FILE"
done

echo "Generated javascript polyfill: $OUTPUT_FILE";