Pod::Spec.new do |s|
  s.name = "LiquidCore"
  s.version = "0.7.0"
  s.summary = "Provides Node.js virtual machines to run inside iOS apps."
  s.description = <<-DESC
LiquidCore enables Node.js virtual machines to run inside iOS apps. It provides a complete runtime environment, including a virtual file system.
  DESC

  s.homepage = "https://github.com/LiquidPlayer/LiquidCore"
  s.license = {:type => "MIT", :file => "../LICENSE.md"}

  s.author = {"Eric Lange" => "eric@flicket.tv"}

  s.platform = :ios, '11.0'

  s.source = {:git => "https://github.com/LiquidPlayer/LiquidCore.git", :tag => "#{s.version}"}

  s.exclude_files = [
  ]

  s.source_files =
	 # libuv
	 "../deps/node-10.15.3/deps/uv/src/fs-poll.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/inet.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/threadpool.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/timer.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/uv-data-getter-setters.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/uv-common.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/version.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/async.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/core.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/dl.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/fs.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/getaddrinfo.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/getnameinfo.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/loop.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/loop-watcher.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/pipe.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/poll.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/process.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/signal.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/stream.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/tcp.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/thread.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/tty.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/udp.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/proctitle.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/linux-core.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/linux-inotify.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/linux-syscalls.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/pthread-fixes.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/android-ifaddrs.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/procfs-exepath.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/sysinfo-loadavg.{c,h}",
     "../deps/node-10.15.3/deps/uv/src/unix/sysinfo-memory.{c,h}",

    # cares
	"../deps/node-10.15.3/deps/cares/src/ares_android.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_cancel.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares__close_sockets.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_create_query.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_data.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_destroy.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_expand_name.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_expand_string.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_fds.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_free_hostent.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_free_string.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_gethostbyaddr.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_gethostbyname.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares__get_hostent.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_getnameinfo.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_getopt.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_getsock.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_init.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_library_init.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_llist.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_mkquery.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_nowarn.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_options.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_aaaa_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_a_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_mx_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_naptr_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_ns_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_ptr_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_soa_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_srv_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_parse_txt_reply.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_process.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_query.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares__read_line.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_search.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_send.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_strcasecmp.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_strdup.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_strerror.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_strsplit.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_timeout.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares__timeval.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_version.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/ares_writev.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/bitncmp.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/inet_net_pton.{c,h}",
	"../deps/node-10.15.3/deps/cares/src/inet_ntop.{c,h}",

    # http_parser
    "../deps/node-10.15.3/deps/http_parser/http_parser.{c,h}",

    # nghttp2
    "../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_buf.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_callbacks.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_debug.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_frame.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_hd.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_hd_huffman.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_hd_huffman_data.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_helper.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_http.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_map.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_mem.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_npn.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_option.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_outbound_item.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_pq.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_priority_spec.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_queue.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_rcbuf.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_session.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_stream.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_submit.{c,h}",
	"../deps/node-10.15.3/deps/nghttp2/lib/nghttp2_version.{c,h}",

    # openssl
    "../deps/node-10.15.3/deps/openssl/openssl/ssl/bio_ssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/d1_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/d1_msg.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/d1_srtp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/methods.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/pqueue.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/record/dtls1_bitmap.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/record/rec_layer_d1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/record/rec_layer_s3.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/record/ssl3_buffer.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/record/ssl3_record.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/s3_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/s3_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/s3_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/s3_msg.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_cert.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_ciph.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_conf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_init.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_mcnf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_rsa.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_sess.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_stat.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_txt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/ssl_utst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/statem/statem.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/statem/statem_clnt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/statem/statem_dtls.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/statem/statem_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/statem/statem_srvr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/t1_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/t1_ext.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/t1_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/t1_reneg.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/t1_trce.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/ssl/tls_srp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_cfb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_core.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_ige.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_misc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_ofb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/aes/aes_wrap.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_bitstr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_d2i_fp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_digest.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_dup.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_gentm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_i2d_fp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_int.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_mbstr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_object.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_octet.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_strex.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_strnid.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_time.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_type.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_utctm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_utf8.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/a_verify.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/ameth_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn1_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn1_gen.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn1_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn1_par.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn_mime.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn_moid.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn_mstbl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/asn_pack.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/bio_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/bio_ndef.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/d2i_pr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/d2i_pu.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/evp_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/f_int.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/f_string.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/i2d_pr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/i2d_pu.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/n_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/nsseq.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/p5_pbe.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/p5_pbev2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/p5_scrypt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/p8_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/t_bitst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/t_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/t_spki.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_dec.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_fre.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_new.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_scn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_typ.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/tasn_utl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_algor.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_bignum.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_info.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_int64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_long.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_sig.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_spki.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/asn1/x_val.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/arch/async_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/arch/async_posix.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/arch/async_win.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/async.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/async_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/async/async_wait.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bf/bf_cfb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bf/bf_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bf/bf_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bf/bf_ofb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bf/bf_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/b_addr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/b_dump.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/b_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/b_sock.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/b_sock2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bf_buff.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bf_lbuf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bf_nbio.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bf_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bio_cb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bio_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bio_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bio_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_acpt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_bio.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_conn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_dgram.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_fd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_file.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_log.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_mem.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bio/bss_sock.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/blake2/blake2b.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/blake2/blake2s.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/blake2/m_blake2b.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/blake2/m_blake2s.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_add.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_asm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_blind.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_const.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_ctx.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_depr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_dh.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_div.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_exp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_exp2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_gcd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_gf2m.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_intern.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_kron.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_mod.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_mont.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_mpi.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_mul.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_nist.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_prime.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_rand.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_recp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_shift.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_sqr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_sqrt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_srp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_word.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/bn/bn_x931p.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/buffer/buf_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/buffer/buffer.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/camellia.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_cfb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_ctr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_misc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/camellia/cmll_ofb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cast/c_cfb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cast/c_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cast/c_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cast/c_ofb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cast/c_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/chacha/chacha_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cmac/cm_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cmac/cm_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cmac/cmac.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_att.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_cd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_dd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_env.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_ess.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_io.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_kari.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_pwri.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_sd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cms/cms_smime.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_api.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_def.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_mall.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_mod.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_sap.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/conf/conf_ssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cpt_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cryptlib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_b64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_log.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_oct.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_policy.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_sct.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_sct_ctx.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_vfy.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ct/ct_x509v3.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/cversion.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/cbc_cksm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/cbc_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/cfb64ede.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/cfb64enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/cfb_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/des_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/ecb3_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/ecb_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/fcrypt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/fcrypt_b.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/ofb64ede.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/ofb64enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/ofb_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/pcbc_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/qud_cksm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/rand_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/rpc_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/set_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/str2key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/des/xcbc_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_check.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_depr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_gen.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_kdf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dh/dh_rfc5114.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_depr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_gen.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_ossl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dsa/dsa_vrf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_dl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_dlfcn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_openssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_vms.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/dso/dso_win32.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ebcdic.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/curve25519.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec2_mult.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec2_oct.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec2_smpl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_check.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_curve.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_cvt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_kmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_mult.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_oct.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ec_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecdh_kdf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecdh_ossl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecdsa_ossl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecdsa_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecdsa_vrf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/eck_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_mont.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_nist.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_nistp224.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_nistp256.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_nistp521.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_nistputil.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_oct.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecp_smpl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ec/ecx_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_all.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_cnf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_cryptodev.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_ctrl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_dyn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_fat.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_init.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_list.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_openssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_rdrand.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/eng_table.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_asnmth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_cipher.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_dh.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_digest.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_dsa.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_eckey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_pkmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_rand.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/engine/tb_rsa.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/err/err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/err/err_all.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/err/err_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/bio_b64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/bio_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/bio_md.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/bio_ok.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/c_allc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/c_alld.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/cmeth_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/digest.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_aes.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_aes_cbc_hmac_sha1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_aes_cbc_hmac_sha256.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_bf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_camellia.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_cast.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_chacha20_poly1305.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_des.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_des3.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_idea.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_old.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_rc2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_rc4.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_rc4_hmac_md5.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_rc5.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_seed.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/e_xcbc_d.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/encode.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_cnf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_pbe.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/evp_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_md2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_md4.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_md5.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_md5_sha1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_mdc2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_ripemd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_sha1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_sigver.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/m_wp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/names.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p5_crpt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p5_crpt2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_dec.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_open.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_seal.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/p_verify.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/pmeth_fn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/pmeth_gn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/pmeth_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/evp/scrypt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ex_data.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/getenv.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/hmac/hm_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/hmac/hm_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/hmac/hmac.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/idea/i_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/idea/i_cfb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/idea/i_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/idea/i_ofb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/idea/i_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/init.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/kdf/hkdf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/kdf/kdf_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/kdf/tls1_prf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/lhash/lh_stats.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/lhash/lhash.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/md4/md4_dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/md4/md4_one.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/md5/md5_dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/md5/md5_one.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mdc2/mdc2_one.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mdc2/mdc2dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mem.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mem_clr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mem_dbg.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/mem_sec.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/cbc128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/ccm128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/cfb128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/ctr128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/cts128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/gcm128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/ocb128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/ofb128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/wrap128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/modes/xts128.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_dir.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_fips.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_fopen.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_init.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_str.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/o_time.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/objects/o_names.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/objects/obj_dat.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/objects/obj_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/objects/obj_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/objects/obj_xref.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_asn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_cl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_ext.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_ht.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_srv.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/ocsp_vfy.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ocsp/v3_ocsp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_all.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_info.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_oth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_pk8.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_pkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_x509.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pem_xaux.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pem/pvkfmt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_add.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_asn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_attr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_crpt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_crt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_decr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_init.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_key.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_kiss.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_mutl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_npas.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_p8d.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_p8e.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_sbag.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/p12_utl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs12/pk12err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/bio_pk7.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_attr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_doit.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_mime.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pk7_smime.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/pkcs7/pkcs7err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/poly1305/poly1305.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/md_rand.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_egd.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_unix.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_vms.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/rand_win.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rand/randfile.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc2/rc2_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc2/rc2_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc2/rc2_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc2/rc2cfb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc2/rc2ofb64.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc4/rc4_enc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rc4/rc4_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ripemd/rmd_dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ripemd/rmd_one.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_ameth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_chk.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_crpt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_depr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_gen.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_none.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_null.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_oaep.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_ossl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_pk1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_pmeth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_pss.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_saos.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_ssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_x931.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/rsa/rsa_x931g.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/seed/seed.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/seed/seed_cbc.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/seed/seed_cfb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/seed/seed_ecb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/seed/seed_ofb.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/sha/sha1_one.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/sha/sha1dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/sha/sha256.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/sha/sha512.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/srp/srp_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/srp/srp_vfy.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/stack/stack.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/threads_none.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/threads_pthread.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/threads_win.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_asn1.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_conf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_req_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_req_utils.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_rsp_print.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_rsp_sign.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_rsp_utils.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_rsp_verify.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ts/ts_verify_ctx.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/txt_db/txt_db.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ui/ui_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ui/ui_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ui/ui_openssl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/ui/ui_util.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/uid.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/whrlpool/wp_block.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/whrlpool/wp_dgst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/by_dir.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/by_file.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/t_crl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/t_req.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/t_x509.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_att.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_cmp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_d2.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_def.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_ext.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_lu.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_meth.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_obj.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_r2x.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_req.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_set.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_trs.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_txt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_v3.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_vfy.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509_vpm.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509cset.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509name.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509rset.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509spki.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x509type.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_all.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_attrib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_crl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_exten.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_name.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_pubkey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_req.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_x509.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509/x_x509a.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_cache.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_data.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_map.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_node.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/pcy_tree.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_addr.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_akey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_akeya.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_alt.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_asid.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_bcons.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_bitst.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_conf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_cpols.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_crld.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_enum.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_extku.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_genn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_ia5.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_info.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_int.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_lib.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_ncons.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_pci.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_pcia.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_pcons.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_pku.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_pmaps.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_prn.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_purp.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_skey.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_sxnet.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_tlsf.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3_utl.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/crypto/x509v3/v3err.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/engines/e_capi.{c,h}",
	"../deps/node-10.15.3/deps/openssl/openssl/engines/e_padlock.{c,h}",

    # node_lib
	"../deps/node-10.15.3/src/async_wrap.{cc,h}",
	"../deps/node-10.15.3/src/bootstrapper.{cc,h}",
	"../deps/node-10.15.3/src/callback_scope.{cc,h}",
	"../deps/node-10.15.3/src/cares_wrap.{cc,h}",
	"../deps/node-10.15.3/src/connection_wrap.{cc,h}",
	"../deps/node-10.15.3/src/connect_wrap.{cc,h}",
	"../deps/node-10.15.3/src/debug_utils.{cc,h}",
	"../deps/node-10.15.3/src/env.{cc,h}",
	"../deps/node-10.15.3/src/exceptions.{cc,h}",
	"../deps/node-10.15.3/src/fs_event_wrap.{cc,h}",
	"../deps/node-10.15.3/src/handle_wrap.{cc,h}",
	"../deps/node-10.15.3/src/heap_utils.{cc,h}",
	"../deps/node-10.15.3/src/js_stream.{cc,h}",
	"../deps/node-10.15.3/src/module_wrap.{cc,h}",
#	"../deps/node-10.15.3/src/node.{cc,h}", <--- We are overriding
	"../deps/node-10.15.3/src/node_api.{cc,h}",
	"../deps/node-10.15.3/src/node_buffer.{cc,h}",
	"../deps/node-10.15.3/src/node_config.{cc,h}",
	"../deps/node-10.15.3/src/node_constants.{cc,h}",
	"../deps/node-10.15.3/src/node_contextify.{cc,h}",
	"../deps/node-10.15.3/src/node_domain.{cc,h}",
	"../deps/node-10.15.3/src/node_encoding.{cc,h}",
#	"../deps/node-10.15.3/src/node_file.{cc,h}", <--- We are overriding
	"../deps/node-10.15.3/src/node_http2.{cc,h}",
	"../deps/node-10.15.3/src/node_http_parser.{cc,h}",
	"../deps/node-10.15.3/src/node_messaging.{cc,h}",
	"../deps/node-10.15.3/src/node_options.{cc,h}",
	"../deps/node-10.15.3/src/node_os.{cc,h}",
	"../deps/node-10.15.3/src/node_platform.{cc,h}",
	"../deps/node-10.15.3/src/node_perf.{cc,h}",
	"../deps/node-10.15.3/src/node_postmortem_metadata.{cc,h}",
	"../deps/node-10.15.3/src/node_process.{cc,h}",
	"../deps/node-10.15.3/src/node_serdes.{cc,h}",
	"../deps/node-10.15.3/src/node_trace_events.{cc,h}",
	"../deps/node-10.15.3/src/node_types.{cc,h}",
	"../deps/node-10.15.3/src/node_url.{cc,h}",
	"../deps/node-10.15.3/src/node_util.{cc,h}",
	"../deps/node-10.15.3/src/node_v8.{cc,h}",
	"../deps/node-10.15.3/src/node_stat_watcher.{cc,h}",
	"../deps/node-10.15.3/src/node_watchdog.{cc,h}",
	"../deps/node-10.15.3/src/node_worker.{cc,h}",
	"../deps/node-10.15.3/src/node_zlib.{cc,h}",
	"../deps/node-10.15.3/src/node_i18n.{cc,h}",
	"../deps/node-10.15.3/src/pipe_wrap.{cc,h}",
#	"../deps/node-10.15.3/src/process_wrap.{cc,h}", <--- We are overriding
	"../deps/node-10.15.3/src/sharedarraybuffer_metadata.{cc,h}",
	"../deps/node-10.15.3/src/signal_wrap.{cc,h}",
	"../deps/node-10.15.3/src/spawn_sync.{cc,h}",
	"../deps/node-10.15.3/src/string_bytes.{cc,h}",
	"../deps/node-10.15.3/src/string_decoder.{cc,h}",
	"../deps/node-10.15.3/src/stream_base.{cc,h}",
	"../deps/node-10.15.3/src/stream_pipe.{cc,h}",
	"../deps/node-10.15.3/src/stream_wrap.{cc,h}",
	"../deps/node-10.15.3/src/tcp_wrap.{cc,h}",
	"../deps/node-10.15.3/src/timer_wrap.{cc,h}",
	"../deps/node-10.15.3/src/tracing/agent.{cc,h}",
	"../deps/node-10.15.3/src/tracing/node_trace_buffer.{cc,h}",
	"../deps/node-10.15.3/src/tracing/node_trace_writer.{cc,h}",
	"../deps/node-10.15.3/src/tracing/trace_event.{cc,h}",
	"../deps/node-10.15.3/src/tracing/traced_value.{cc,h}",
	"../deps/node-10.15.3/src/tty_wrap.{cc,h}",
	"../deps/node-10.15.3/src/udp_wrap.{cc,h}",
	"../deps/node-10.15.3/src/util.{cc,h}",
	"../deps/node-10.15.3/src/uv.{cc,h}",
	"../deps/node-10.15.3/src/node_code_cache_stub.{cc,h}",
	"../deps/node-10.15.3/src/node_crypto.{cc,h}",
	"../deps/node-10.15.3/src/node_crypto_bio.{cc,h}",
	"../deps/node-10.15.3/src/node_crypto_clienthello.{cc,h}",
	"../deps/node-10.15.3/src/tls_wrap.{cc,h}",

    # V82JSC
    "V82JSC/**/*.{cpp,h}",
    "../deps/utfcpp/**/*.{h}",
    "../deps/JavaScriptCore/private/*.h",
    "../deps/Apple/**/*.h",

    # Dynamically generated files.
    #"LiquidCoreiOS/LiquidCore/gen/polyfill.c",
    #"LiquidCoreiOS/LiquidCore/gen/node_javascript.c",
    #"LiquidCoreiOS/LiquidCore/gen/node_provider.h",

    # LiquidCore node modifications
    "LiquidCoreCommon/node/*",
    "LiquidCoreCommon/include/*.h",

    # API
    "LiquidCoreiOS/LiquidCore/Headers/*.h",
    "LiquidCoreiOS/LiquidCore/API/*.{h,m,cpp}"

  s.public_header_files = [
      "LiquidCoreiOS/LiquidCore/Headers/*.h"
  ]

  s.private_header_files = [
        "../deps/node-10.15.3/src/*.h",
        "../deps/node-10.15.3/deps/cares/include/*.h",
        "../deps/node-10.15.3/deps/http_parser/*.h",
        "../deps/node-10.15.3/deps/nghttp2/lib/**/*.h",

        "../deps/node-10.15.3/deps/uv/include/pthread-barrier.h",
        "../deps/node-10.15.3/deps/uv/include/tree.h",
        "../deps/node-10.15.3/deps/uv/include/uv-darwin.h",
        "../deps/node-10.15.3/deps/uv/include/uv-errno.h",
        "../deps/node-10.15.3/deps/uv/include/uv-threadpool.h",
        "../deps/node-10.15.3/deps/uv/include/uv-unix.h",
        "../deps/node-10.15.3/deps/uv/include/uv-version.h",
        "../deps/node-10.15.3/deps/uv/include/uv.h",

        "../deps/node-10.15.3/deps/v8/include/**/*.h"
  ]


  # --- Tests ――――――――――-――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #

  # s.test_spec 'Tests' do |test_spec|
  #   test_spec.source_files = [
  #       'LiquidCoreiOS/LiquidCoreTests/**/*.{m,cpp,cc}',
  #       'deps/node-8.9.3/deps/v8/src/extensions/gc-extension.c',
  #       'deps/node-8.9.3/deps/v8/src/flags.c',
  #       'deps/node-8.9.3/deps/v8/test/cctest/print-extension.c',
  #       'deps/node-8.9.3/deps/v8/test/cctest/profiler-extension.c',
  #   ]
  #
  #   test_spec.resources = [
  #       'LiquidCoreiOS/LiquidCoreTests/Resources'
  #   ]
  #
  #   test_spec.exclude_files = [
  #       'LiquidCoreiOS/LiquidCore/ConsoleView/ConsoleView.xib'
  #   ]
  #
  # end

  # Preserve header include paths.
  s.preserve_paths = [
    "../deps/node-10.15.3/deps/v8/include",
    "../deps/node-10.15.3/deps/v8",

    "../deps/openssl-1.0.2o/include-ios",
    "../deps/node-10.15.3/src",
    "../deps/node-10.15.3/deps/nghttp2/lib/includes",
    "LiquidCoreiOS/LiquidCore/node-8.9.3/node",
  ]

  # ――― Project Settings ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #

  s.requires_arc = true

  s.libraries = [
      'z',
      'c++'
  ]
  s.frameworks = "JavaScriptCore"

  # Generate some of the source files so that CocoaPods may pick them up.
  #s.prepare_command = <<-CMD
  #    # Generate node_javascript.c
  #    bash LiquidCoreiOS/scripts/generate_node_javascript.sh
  #    # Generate node_provider.h
  #    bash LiquidCoreiOS/scripts/generate_node_provider.sh
  #    # Generate V82JSC polyfills
  #    bash LiquidCoreiOS/scripts/generate_javascript_polyfills.sh
  #CMD

  s.xcconfig = {
      # System Header Search Paths
      :HEADER_SEARCH_PATHS => [
          # OTHER_CPLUSPLUSFLAGS -I includes
          "$(PODS_TARGET_SRCROOT)/../deps/node-10.15.3/deps/v8/include",
          "${PODS_TARGET_SRCROOT}/../deps/node-10.15.3/deps/v8",
          # Other includes.
          "$(PODS_TARGET_SRCROOT)/../deps/node-10.15.3/src",
          "$(PODS_TARGET_SRCROOT)/../deps/node-10.15.3/deps/nghttp2/lib/includes",
          #"$(PODS_TARGET_SRCROOT)/LiquidCoreiOS/LiquidCore/node-8.9.3/node"
      ].join(' '),

      :OTHER_CFLAGS => [
          '-D_DARWIN_USE_64_BIT_INODE=1',
          '-D_DARWIN_UNLIMITED_SELECT=1',
          '-DHTTP_PARSER_STRICT=0',
          '-D_LARGEFILE_SOURCE',
          '-D_FILE_OFFSET_BITS=64',
          '-D_GNU_SOURCE',
          '-DHAVE_CONFIG_H',
          '-DNODE_PLATFORM=\'"ios"\'',
          '-DNODE_ARCH=\'"${NODE_ARCH}"\'',
          '-DNODE_WANT_INTERNALS=1',
          '-DV8_DEPRECATION_WARNINGS=1',
          '-DNODE_OPENSSL_SYSTEM_CERT_PATH=\'""\'',
          '-DHAVE_INSPECTOR=0',
          '-DNODE_SHARED_MODE',
          '-DNODE_USE_V8_PLATFORM=1',
          '-DHAVE_OPENSSL=1',
          '-DHTTP_PARSER_STRICT=0',

          '-D__POSIX__',
          '-D_REENTRANT=1',
          '-D_DARWIN_USE_64_BIT_INODE=1',
          '-D_LARGEFILE_SOURCE',
          '-D_FILE_OFFSET_BITS=64',
          '-D_GNU_SOURCE',
          '-DHAVE_CONFIG_H',
          '-D_GLIBCXX_USE_C99_MATH',

          '-DHTTP_MAX_HEADER_SIZE=8192',
          '-DHTTP_PARSER_STRICT=0',

          '-D_U_=',
          '-DBUILDING_NGHTTP2',
          '-DNGHTTP2_STATICLIB',

          '-DOPENSSL_NO_HW',
          '-DOPENSSL_NO_ASM',
          '-DDSO_DLFCN',
          '-DHAVE_DLFCN_H',
          '-DOPENSSL_THREADS',
          '-DOPENSSL_NO_DYNAMIC_ENGINE',
          '-DOPENSSL_PIC',
          '-DOPENSSLDIR=\'"/etc/ssl"\'',
          '-DENGINESDIR=\'"/dev/null"\'',
          '-DTERMIOS'

      ].join(' '),

      :OTHER_CPLUSPLUSFLAGS => [
          '-Wno-inconsistent-missing-override',
          '-DV8_OS_MACOSX',
          '-DV8_FAST_TLS_SUPPORTED_NOXXX',
          '-DNODE_WANT_INTERNALS=1',
          '-DNODE_PLATFORM=\"iOS\"',
          '-DNODE_ARCH=\"arm64\"',
          '-DV8_DEPRECATION_WARNINGS=1',
          '-DBUILDING_NGHTTP2',
          '-DNODE_USE_V8_PLATFORM=1',
          '-DHAVE_INSPECTOR=0',
          '-DV8_INSPECTOR_USE_STL=1',
          '-DV8_INSPECTOR_USE_OLD_STL=1',
          '-DHAVE_OPENSSL=1',
          '-DHTTP_PARSER_STRICT=0',
          '-D_GLIBCXX_USE_C99_MATH',
          '-DHAVE_DTRACE=1',
      ].join(' '),

      # Disable warnings
      :CLANG_WARN_COMMA => 'NO',
      :CLANG_WARN_DOCUMENTATION_COMMENTS => 'NO',
      :GCC_WARN_64_TO_32_BIT_CONVERSION => 'NO',
      :GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS => 'NO',
      :GCC_WARN_UNUSED_VARIABLE => 'NO',
      :GCC_WARN_UNINITIALIZED_AUTOS => 'NO',
      :CLANG_WARN_UNREACHABLE_CODE => 'NO'
  }

  s.resources = [
  ]

end
